### ISSUE TITLE
The Gradle sample application is severely out of date

### ISSUE THREAD

**Issue by carlspring** [Contrast-Security-OSS/contrast-gradle-plugin#15]
# Task Description

The [Gradle example application](https://github.com/Contrast-Security-OSS/Contrast-Sample-Gradle-Application) is severely out of date.

I'm raising the issue here, as there is no issue tracker for the sample app repository.

# Task List

The following tasks should be considered:
* [ ] Upgrade to a more recent version of Gradle.
* [ ] Upgrade to a more recent version of Spring + Spring Data which supports more modern versions of MongoDB.
* [ ] Set up a `docker-compose` and/or use `testcontainers` to start a Docker container running MongoDB.
* [ ] Support more recent versions of the JDK.
* [ ] There should be an `application.yml` where the MongoDB connection details can be configured.

**Comment by gilday** [comment]
@carlspring you're right, this is out of date. Have you seen https://docs.contrastsecurity.com/en/install-with-existing-gradle-project-with-docker.html ? It it is a tutorial that references a more modern example https://github.com/Contrast-Security-OSS/contrast-java-examples/tree/gradle-docker-complete
